name: "Github Events Trigger"
description: "Action for Github Events Trigger"
author: "fncolon"
inputs:
  chat:
    description: "Chat to send: chat id or @channel_name"
    required: true
  token:
    description: "Telegram Bot token"
    required: true
  status:
    description: "Job status"
    required: true
  iu_title:
    description: "Issue Title"
    default: ${{ github.event.issue.title }}
    required: false
  iu_num:
    description: "Issue Number"
    default: ${{ github.event.issue.number }}
    required: false
  iu_actor:
    description: "Issue Triggerer"
    default: ${{ github.event.issue.user.login }}
    required: false
  iu_com:
    description: "Issue Comment"
    default: ${{github.event.comment.body}}
    required: false
  pr_state:
    description: "State of the PR"
    default: ${{ github.event.action }}
    required: false
  pr_num:
    description: "PR Number"
    default: ${{ github.event.number }}
    required: false
  pr_title:
    description: "Title of the PR"
    default: ${{ github.event.pull_request.title }}
    required: false
  pr_body:
    description: "Body/Contents of the PR"
    default: ${{ github.event.pull_request.body }}
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "repeat"
  color: "green"
